# -*- coding: utf-8 -*-
"""MIP_HW5_Q2_98102527.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgMZt5pTeyOH6riP90HRm0nAMNnFszW0

## Import Libraries
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.feature import graycomatrix, graycoprops

"""## GLCM from scrtch (angle=0, distance=1)"""

def calc_glcm(image, level=256, distance=1):
    glcm = np.zeros((level, level))
    for i in range(gray_image.shape[1]-distance):
        for j in range(gray_image.shape[0]):
            this_level = gray_image[j, i]
            next_level = gray_image[j, i+distance]
            glcm[this_level, next_level] += 1
    return glcm

image = cv2.imread('Q2.jpg')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
glcm = calc_glcm(gray_image)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.imshow(glcm)
plt.title('GLCM Matrix')
plt.subplot(1, 2, 2)
log_glcm = glcm.copy()
log_glcm[glcm == 0] = 1e-9
log_glcm = np.log(log_glcm)
plt.imshow(log_glcm)
plt.title('Log-GLCM Matrix')
plt.show()

glcm = glcm[:, :, np.newaxis, np.newaxis]
homogeneity = graycoprops(glcm, 'homogeneity')
dissimilarity = graycoprops(glcm, 'dissimilarity')
contrast = graycoprops(glcm, 'contrast')
asm = graycoprops(glcm, 'ASM')
correlation = graycoprops(glcm, 'correlation')
energy = graycoprops(glcm, 'energy')

print('Homogeneity:', homogeneity)
print('Dissimilarity:', dissimilarity)
print('Contrast:', contrast)
print('ASM:', asm)
print('Correlation:', correlation)
print('Energy:', energy)

"""## GLCM with Built-in Functions (angle=[0, pi/2, pi, 3*pi/3])"""

distance = [1]
angles = [0, np.pi/2, np.pi, 3*np.pi/2] # right, up, left, dowm

glcm = graycomatrix(gray_image, distances=distance, angles=angles, levels=256, symmetric=False)

pos = ['right', 'up', 'left', 'down']
plt.figure(figsize=(10, 6))
for i in range(4):
    local_glcm = glcm[:, :, 0, i].copy()
    local_log_glcm = local_glcm.copy()
    local_log_glcm = np.log(local_log_glcm + 1e-9)
    plt.subplot(2, 4, i+1)
    plt.imshow(local_glcm)
    plt.title('GLCM, ' + pos[i])
    plt.subplot(2, 4, 4+i+1)
    plt.imshow(local_log_glcm)
    plt.title('Log-GLCM, ' + pos[i])

homogeneity = graycoprops(glcm, 'homogeneity')
dissimilarity = graycoprops(glcm, 'dissimilarity')
contrast = graycoprops(glcm, 'contrast')
asm = graycoprops(glcm, 'ASM')
correlation = graycoprops(glcm, 'correlation')
energy = graycoprops(glcm, 'energy')

print('Homogeneity:', homogeneity)
print('Dissimilarity:', dissimilarity)
print('Contrast:', contrast)
print('ASM:', asm)
print('Correlation:', correlation)
print('Energy:', energy)